### ISSUE TITLE
テスト　ー変数ー

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#1]
変数で躓いてます！

**Comment by Dk-Roar** [comment]
tesuteus

**Comment by LunaChevalier** [comment]
変数は入れ物、変数名は入れ物の名前です

たとえば
```
String printString = "Hello World"
```
というのは、下のようなイメージになります
![20170220003118](https://user-images.githubusercontent.com/5876235/33474903-b8d62620-d6bf-11e7-8835-18c0f2101d75.jpg)
