### ISSUE TITLE
FizzBuzz 疑問点（倍数）

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#11]
倍数の書き方が自分で調べてみてもよく分かりませんでした。
余りの数が0ということなので、こんな感じになるんだろうと思いました。
どう書くのかはもう少し考えてみますので、とりあえずこれに関して評価をお願いします。

if(i % 3 == 0)

**Comment by LunaChevalier** [comment]
完璧です!  
文法と3の倍数の書き方、どちらも正解です

後はiに色々値を入れて、3の倍数でFizzが表示されるかされないかの確認をしてみて下さい

**Comment by hibikisameta** [comment]
ありがとうございます！
しかしまだエラーが出るので引き続き考えます。

**Comment by LunaChevalier** [comment]
解決に時間がかかりそうなら、1時間を目処に質問して下さいね

**Comment by LunaChevalier** [comment]
次からで大丈夫なので、何か分からないところが出たら、その時点で調べる前にわからない内容をissueのタイトルに書いて立ててから調べて下さい  
その後で調べてみて、1時間を目処に立てたissueに、解決出来たらその答え、解決出来なかったらどう調べたのか教えて下さい

**Comment by hibikisameta** [comment]
了解しました。
