### ISSUE TITLE
【疑問】eclipseの保管→importの自動修正

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#12]
importが出てきて実行が押せませんでした。

eclipseには、保管後importを自動で追加または削除してくれる機能があると知りました。しかし、その後実行が押せなくなり（エラー出ず）、import文を消してみたら赤波線が多数出てきました。

ー調べた結果ー
「java import 保管」「eclipse import 追加」等で調べましたが、結局eclipseにはimportを自動調整する機能があるということまでしか分かりませんでした。
なぜ実行できないのか、またエラー表示もないのかは不明なままです。

よろしくお願いします。

![image](https://user-images.githubusercontent.com/34155360/33702993-637e7818-db69-11e7-8aea-6b160574e183.png)

**Comment by Dk-Roar** [comment]
importの自動保管自体には問題ないです。

むしろそれらが無いとエラーが出ます(赤線が出てるとこですね)

おそらく、12行目のreadLineの処理で入力受付状態になって処理が止まっているのかなと思います。

どこまで処理が進んだか確認する手段の１つとして、System.out.printlnを途中に挟むというものがあります。

今回だとreadlineの前後に記述することで、readlineが終わったかが判別できると思います。

**Comment by Dk-Roar** [comment]
あと条件分岐の動作確認のために、一旦変数resに数値をいれて実行したりしてみてください(๑･̑◡･̑๑)

※提出の時は元に戻してくださいね〜。

**Comment by hibikisameta** [comment]
明日やってみます。ありがとうございます。

**Comment by hibikisameta** [comment]
やはり12行目で処理が止まっていましたので、readlineは終わってないこととなります。

**Comment by Dk-Roar** [comment]
readlineはコンソールからの入力を受け付ける状態になって、入力されたらその値を変数に入れる機能になります。

なのでコンソールに何かしらの値を入力してエンターを押さないと次に進みません。

実行結果が表示されている画面に値を入力してエンターを押して見てください。

**Comment by hibikisameta** [comment]
了解です。
仰ってる意味は分かるのですが、頭がちゃんと整理出来てなくてもう少し考えたいので待ってもらえますか？

**Comment by hibikisameta** [comment]
すみません。resに代入することは分かってはいるんですが、色々試しましたが入力する場所が分かりませんでした。

**Comment by LunaChevalier** [comment]
`readLine`の直前の行に`System.out.println`で何か表示するプログラムを書いて下さい  
実行したら表示される所をクリックしてキーボード入力すると、文字が入るのでそれで数値を入力してエンターして下さい(伝わるかな…)

**Comment by hibikisameta** [comment]
出来ました。ありがとうございます、お手数おかけしました。
あとはどちらにも当てはまらない数が出てこなかったので、そこを表示させるようやってみます。
