### ISSUE TITLE
3と5両方当てはまる場合の条件式

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#14]
FizzBuzzで3と5どっちにも当てはまる場合の書き方が分かりませんので、今から1時間調べます。

**Comment by hibikisameta** [comment]
調べた結果、論理積 && を使うのではないかと思ったので、
　　if(i = i % 3 && i % 5 == 0)
と書いてみました。

**Comment by LunaChevalier** [comment]
とっても惜しいです  
考え方はあっているので、後は書き方ですね

今回みたいにプログラムを書いたら、1度動作確認して、どうなったか教えて下さーい

**Comment by hibikisameta** [comment]
他にもエラーがいくつかあるんですが、一つ一つエラーごとにissueを立てた方がいいですか？

**Comment by LunaChevalier** [comment]
今回は書き方について調べてるので、このissueで大丈夫です

一番最初の問題が解決したけど、別の問題が出た時(書き方は合ってるみたいだけど、思った動作になってないなど)、また別のissue立てて下さい

**Comment by hibikisameta** [comment]
了解しました。訂正します。

if(i % 3 == 0 && i % 5 == 0)
