### ISSUE TITLE
課題「素数判定」をeclipseで書く場合

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#17]
新規→javaプロジェクトで作成という流れになるんでしょうか？

**Comment by LunaChevalier** [comment]
ブランチを素数判定用のブランチに変えて提出して下さい

**Comment by hibikisameta** [comment]
出来ました。
ここから新規のjavaプロジェクトでいいですか？
それともクラスで作った方がいいですか？

**Comment by LunaChevalier** [comment]
同じクラスで大丈夫です

**Comment by hibikisameta** [comment]
ブランチをPrimeNumberに変えたんですが、クラス自体まだない状態です。
なのでこの場合は、クラス作成でいいですよね？

![image](https://user-images.githubusercontent.com/34155360/33869275-38711de8-df4b-11e7-9b8e-89c6104c9707.png)

**Comment by LunaChevalier** [comment]
`ElementProgram.java`でお願いします

ブランチが変わったので、1番最初の状態になっていると思います

**Comment by hibikisameta** [comment]
ElementProgram.javaというクラス名にするということですか？
やってみましたが、完了ボタンが押せませんでした。

また、上の画像にあるJRE システム・ライブラリーに書き込んでも実行が出来ませんでした。

**Comment by LunaChevalier** [comment]
すいません、見間違いしてました…  

新規に`PrimeNumber.java`でお願いします

**Comment by hibikisameta** [comment]
了解しました！
こちらこそ何度もすみません
