### ISSUE TITLE
課題 push

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#19]
課題は最後まで終わりませんでした。
納期が守れずすみません。

pushしようと思ってstatusで確認したところ、develop/PrimeNumber ではなく、bin/ と src/ が赤文字で出てきました。
一応addしてみたのですが、これの意味が分からないためcommitのメッセージを何と書いていいのかが分かりかねます。

**Comment by LunaChevalier** [comment]
まず、自分が編集した覚えのない、正体不明のファイルやフォルダが出てきた時、それらを`add`したり`push`するのは良くないので、今後はしないようにして下さい  
大抵の場合、自分の操作ミスで全く関係ないファイルを編集してたり、コンパイルやビルド時に自動生成されたファイルになります  
今回、`src`は提出のに必要なファイルなので問題ないですが、`bin`はgitの設定ファイル(細かい事はwikiに書きます)なので、`push`してはいけない内容です

**Comment by hibikisameta** [comment]
分かりました、気を付けます。

**Comment by LunaChevalier** [comment]
後、納期に間に合わなかったので、どんな作業をしてそれぞれどれ位時間がかかったのか教えて下さい(大体で大丈夫です)

**Comment by hibikisameta** [comment]
流れは頭の中で想像がついたのですが、素数の書き方が分からずに「java 素数 書き方」等で検索をかけました。

昨日会社を出る時には、フローチャートとプログラムの流れを書いて退社しました。
ここでは、1時間弱調べました。

家に帰って再開できたのが12時前くらいだったので、そこから2時間ほど調べましたが自分で解決できなかったので就寝しました。
