### ISSUE TITLE
12/1の宿題

### ISSUE THREAD

**Issue by LunaChevalier** [LunaChevalierGroup/elementProgram#2]
`develop/AgainstNumberGame`と`develop/PrimeNumber`をpushしてください  
中身はどうでもいいですー  
来週からで大丈夫ですー

**Comment by LunaChevalier** [comment]
push出来るかもしれないので、挑戦してみて下さーい

**Comment by hibikisameta** [comment]
山本記

remote: Permission to LunaChevalierGroup/elementProgram.git denied to hibikisameta.
fatal: unable to access 'https://github.com/LunaChevalierGroup/elementProgram.git/': The requested URL returned error: 403

**Comment by hibikisameta** [comment]
pullはできるんだけどpushができない。

**Comment by hibikisameta** [comment]
山本記
「hibikisameta」がfizzBuzzにpushできる権限が無いかも？
権限の確認をお願いします。

**Comment by LunaChevalier** [comment]
権限付与したよの通知メールが来てると思います

**Comment by hibikisameta** [comment]
山本さんメール送った後に職場へと戻られました。
メールというのは、github上でですか？それともgmailでですか？

申し訳ないですが、pushまで辿り着くのに手間取ってしまい初日から課題を出来そうにありません、、、

**Comment by LunaChevalier** [comment]
アカウント作成時に利用したgmailです

**Comment by hibikisameta** [comment]
了解しました。
ありがとうございます。

**Comment by hibikisameta** [comment]
12月1日の宿題が先ほど終わりました。
草場さん、出勤前にありがとうございました。

**Comment by LunaChevalier** [comment]
確認しました  
今日も1日└(。`･ ω ･´。)┘ｶﾞﾝﾊﾞﾙﾋﾞｨ
