### ISSUE TITLE
今後の課題について

### ISSUE THREAD

**Issue by LunaChevalier** [LunaChevalierGroup/elementProgram#23]
今、素数判定をしていると思いますが、午前中にソースコードの提出をお願いします

午後からは今週末までファイルの入出力を中心に取り組もうと思ってます  
ファイルの入出力についてソースコードを書く時はmasterブランチから新しいブランチを作って下さい(ブランチ名はファイルについて分かる名前なら、何でもいいです)  
詳しい課題は今日にでも展開します

**Comment by hibikisameta** [comment]
素数判定に関しては、金土で再度考えてみたのですが全く浮かんでこず一行も書けませんでしたので、#22のコードと変わりありません。

なので、午前中はjava 教本の続けてやろうと思っています。

**Comment by LunaChevalier** [comment]
もし、進展があったらソースコード反映して下さい

**Comment by LunaChevalier** [comment]
ひとつ忘れてました…

メソッドというのも使い始めるので、それの勉強もして下さい
