### ISSUE TITLE
課題と課題（特化型）

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#25]
この二つは同じ課題でしょうか、それとも別物でしょうか？

また、課題（特化型）には「CSVファイルを読み込んで」と最初の一文にあるのですが、これは自分が作成してそれを読み込むということでしょうか？
CSVファイルがどういうものかは分かったんですが、このファイルの立ち位置といいますか、どこで自分の作るプログラムと絡んでくるのかが理解出来ません。

**Comment by hibikisameta** [comment]
プログラムの中でCSVファイルを作るようですね。
また、ファイル作成の流れはこれだと思いました。

![image](https://user-images.githubusercontent.com/34155360/34135204-7bf082be-e4a2-11e7-8cc3-168d12ca2bd7.png)

**Comment by LunaChevalier** [comment]
最初のCSVファイルは手作りです  

こちらから用意するつもりでしたが、時間が無くて作れてないです…(作り次第プッシュします)  
エクセルでCSVファイルを作れるので、最初はそれでお願いします(CSVファイルの中身は何でもいいです)

**Comment by hibikisameta** [comment]
了解しました。
ありがとうございます。
