### ISSUE TITLE
課題（特化型）のフロー

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#26]
今回は難しく感じるためフローチャートの作成から手間取っています。

また、どのようなロジックになるのか今現在では想像がつきません。
このような場合たとえ滅茶滅茶なフローチャートやプログラムであっても、一度その状態を見せた方がいいですか？

**Comment by LunaChevalier** [comment]
まずは
> ファイルの中身をそのままコンソールに表示する

からフローチャートにしてみましょう  
どうしても出来ないなら、どうして出来ないのかを整理してまた質問して下さい

**Comment by hibikisameta** [comment]
単純に作業の順序が分かりません。

ファイルから情報摘出→　　　？　　　→コンソールに出力

「ファイルから情報摘出」からプログラムの書き方が分からないので、フローチャート上に詳しく書けないんだろうと思います。
また本来であれば、フローチャートは枠内に条件式等を書くはずなのにそれが出来ていません。

**Comment by LunaChevalier** [comment]
> フローチャートは枠内に条件式等を書くはずなのにそれが出来ていません。

条件式が出てくると考えている様ですが、場合によっては出てこないです  
今回のように、ファイルから取得したデータをそのまま表示させるので、果たして条件がいるのか…?というところから考えてみましょう

**Comment by hibikisameta** [comment]
了解しました、一応書いてみますね。

**Comment by hibikisameta** [comment]
![image](https://user-images.githubusercontent.com/34155360/34186503-70115162-e56f-11e7-9aec-d3dd048a1088.png)

**Comment by LunaChevalier** [comment]
合ってます!

**Comment by hibikisameta** [comment]
一応ファイル読み込みのところまでは自分なりにやってみて、今はデータの摘出に着手しています。
