### ISSUE TITLE
csvファイル　見つからない

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#28]
手探りでここまで書いてみたのですが、実行を押すと「ファイルが見つかりません」と出ます。
今から3時くらいまで調べます。

![image](https://user-images.githubusercontent.com/34155360/34192363-eefb1eec-e590-11e7-812e-f68dbd000953.png)

![image](https://user-images.githubusercontent.com/34155360/34192412-3c96474e-e591-11e7-87b5-f7c8b0a1672f.png)

**Comment by hibikisameta** [comment]
14行目の "" の中のファイルをC直下に保存して変えてみたんですが、次は「アクセスが拒否されました。」と表示されました。

これに関してまた調べようと思います。

![image](https://user-images.githubusercontent.com/34155360/34193492-61101cfc-e597-11e7-861a-3b55054b93f7.png)

**Comment by hibikisameta** [comment]
c:\\ディレクトリ名\\ファイル名にしたところ、データを出すところまでは行けましたが数値以外が文字化けしてしまいました。

次はこの原因について調べます。

![image](https://user-images.githubusercontent.com/34155360/34194018-065932aa-e59a-11e7-9d1c-7c8ec2d517c3.png)

**Comment by LunaChevalier** [comment]
ファイルを見つけられるようになりましたが、ファイルが見つからない系列の質問は、フォルダの構成を載せて質問して下さーい

**Comment by hibikisameta** [comment]
初歩的なことで申し訳ないのですが、フォルダの構成を載せろというのは下記の画像のことでいいんでしょうか？

![image](https://user-images.githubusercontent.com/34155360/34197056-26d1fafe-e5a8-11e7-9b9b-48fc4ef39fe8.png)

**Comment by LunaChevalier** [comment]
Eclipseのパッケージエクスプローラーでお願いします

**Comment by hibikisameta** [comment]
これのことですね、了解です。

![image](https://user-images.githubusercontent.com/34155360/34197306-3ab15fbe-e5a9-11e7-9be0-4e4abde5b4c2.png)

**Comment by LunaChevalier** [comment]
それでーす!

そして残念なことに、そこにCSVファイルが無いということは、おそらくそのPCでしか正常に動きません…  
プログラムが完成したら、ファイルとプログラムをプッシュしてもらいますが、これをプルしたらどのPCでも正常に動作する様にして下さい

**Comment by hibikisameta** [comment]
了解です、明日やります。
