### ISSUE TITLE
github 黒い画面

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#3]
有田さんが私にやり方を教えてくれた際に使っていた、githubのコード？を打っていた黒い画面の出し方が分かりません。
初歩的な質問ですみませんが、回答よろしくお願いします。

**Comment by LunaChevalier** [comment]
gitbashの事だと思います

**Comment by Dk-Roar** [comment]
クローンしてきたフォルダ上で右クリック→open git bash で開けますー。

クローンしてきたフォルダには、先頭に .git というフォルダがあるはずなので探してみてください

**Comment by Dk-Roar** [comment]
Git bash hereでしたすみません(´･ω･`)

**Comment by hibikisameta** [comment]
ありがとうございます。
フォルダ上で探してみます。

**Comment by LunaChevalier** [comment]
もし開けたらCLOSEして下さいね！

**Comment by hibikisameta** [comment]
Closes #3.

**Comment by hibikisameta** [comment]
Closes #3.
