### ISSUE TITLE
課題（特化型）　クラスの分け方

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#30]
クラス実装の「1. 書き込み処理」と「2. 編集処理」をどう分けるのかパッとしません。

・ファイルの書き込みとは、どこに書き込むのか？コンソールに出力することなのか？
・編集処理とは？

この二点のワードの意味が分からないので、今から調べます。

**Comment by hibikisameta** [comment]
昼上がりに調べた結果を言いますが、課題は昼前時点で2. 行数を入れて出力 まで終わりました。

![image](https://user-images.githubusercontent.com/34155360/34239462-d832ae72-e64a-11e7-8cbd-1fce8f4ef35b.png)

![image](https://user-images.githubusercontent.com/34155360/34239469-e4521332-e64a-11e7-9772-a6be106bfaff.png)

**Comment by LunaChevalier** [comment]
wikiにあるとおり、1度ファイルの中身をそのまま表示するプログラムをプッシュして下さい

**Comment by hibikisameta** [comment]
githubでpushしようとしました。
①bin/, src/ が出てきました
②src/ だけadd しました
③push すると、このような画像が出てきました。

疑問：今さらかとは思いますが、status やadd では、src/ やsrc/elementProgram～とgit bash上に出るのに、pushでは出来ずブランチ名のdevelop/CustomerInfo を打たないといけないのでしょうか。
FizzBuzzの時はstatus やadd でもブランチ名が出ていたと思うんですが、、

src/ やsrc/element～が何者なのかが分かりません。

①
![image](https://user-images.githubusercontent.com/34155360/34240314-626193ce-e650-11e7-806e-9e44633a25d0.png)

②
![image](https://user-images.githubusercontent.com/34155360/34240341-96babda8-e650-11e7-8c30-dea8b2d399f1.png)

③
![image](https://user-images.githubusercontent.com/34155360/34240423-4abf9760-e651-11e7-8fb5-317d8f7b9232.png)
![image](https://user-images.githubusercontent.com/34155360/34240429-62c6443a-e651-11e7-9042-ae367c33138a.png)

**Comment by LunaChevalier** [comment]
gitは必ずブランチをプッシュします  
ファイルやフォルダをプッシュすることはありません

gitコマンドのwikiを覗いて見て下さい!

**Comment by hibikisameta** [comment]
ブランチをpush するのは分かったんですが、FizzBuzz の時にファイルやフォルダが出てこなかったので焦りました。ありがとうございましたー！

**Comment by LunaChevalier** [comment]
プッシュありがとうございます!

ちらっと確認しましたが
* CSVファイルがプッシュされて無いです  
このままでは私たちの環境では動作しないです…
* 仮にCSVファイルをプッシュしても、今のプログラムでは私たちの環境では動作しないです  
ファイルを指定しているパス(分からないならissue作って下さい)が絶対パスなので、相対パスにして下さい
