### ISSUE TITLE
csvファイル push方法

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#31]
まずこのcsvファイルがどのパソコンでも動くようにするためのpush する方法が分からないので、それについて調べます。

**Comment by hibikisameta** [comment]
調べてみましたが、発見できていません。

**Comment by Dk-Roar** [comment]
取り急ぎですみません

csvファイルがgit管理対象のディレクトリ内に存在しないからだと思います

ソースとか置いてるプロジェクトのディレクトリ内に配置した後、git status → git add → git commit → git push の順でやってみてください

**Comment by Dk-Roar** [comment]
あと指摘を勘違いしている節があるので追記します


・csvファイルをpushする  
これは読み込み対象のファイルがプロジェクトに存在しないため読み込みができないからやって欲しいことです  
サーバーにアップロードして此方に共有する必要があると言うことですね

・どのPCでも動くようにする  
これは前の指摘でもあったように、絶対パスを相対パスに変更するというものです  
対象のファイルがあっても、各パソコンでプロジェクトが配置される場所は様々なわけです  
絶対パス指定だと、かならず指定したパスの位置にファイルが置かれている必要があるため、配置場所が違うとエラーとなります  
相対パスにするとこの問題は回避できます

**Comment by hibikisameta** [comment]
csvファイルをgit のディレクトリ内に移動し、上に書かれた流れをやってみました。
①git status 時に、src/, bin/, CustomerInfo.csv の3つが赤文字だった
②src/, CustomerInfo の2つをadd した
③commit した（src/ と思う）
④develop/CustomerInfo をpush

まずは最初に言われたことをやってみました。
次は絶対パス、相対パスについて調べます。

**Comment by Dk-Roar** [comment]
csvファイルのpushできてます(๑･̑◡･̑๑)

手順も報告の仕方もgoodですね〜。

相対パスについては皆がつまづくとこです…がんばってください٩( ᐛ )و

**Comment by hibikisameta** [comment]
ありがとうございます！

相対パスに関して調べてみたんですが、書き方として
　　File file = new File(“ファイル名”);
という書き方が出てきましたが、まだよく分かりません。
今現在自分の書いているコードとさほど変わらないようにも思えますし、腑に落ちないのでまだ時間かかりそうですね。

**Comment by hibikisameta** [comment]
一応上の書き方でやってみて ”” 内をファイル名のみにしたら通りました。
絶対パス、相対パスと明確に分かる方法はあるんでしょうか？

![image](https://user-images.githubusercontent.com/34155360/34246643-d1edb8c2-e672-11e7-8a20-e45966831db7.png)
