### ISSUE TITLE
相対パス

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#33]
相対パスの書き方について今から調べます。

・絶対パス　―　どのフォルダで作業中でも決まったところから目的のフォルダへ行ける
・相対パス　―　今いるところから目的のフォルダへ行ける

**Comment by hibikisameta** [comment]
調べてみて約束事みたいなものは見つけたのですが、ここからの書き方がよく分かりませんでした。

相対パス指定の方法
・同じ階層にあるものは、そのままファイル名か「./ファイル名」
・下の階層にあるものは、「./フォルダ名/ファイル名」
・上の階層にあるものは、「../ファイル名」
・２階層上にあるものは、「../../ファイル名」
・1階層上にあるフォルダの中のファイルは、「../フォルダ名/ファイル名」

**Comment by hibikisameta** [comment]
昼前までに相対パスを解決することが出来ませんでした。

【疑問】
検索していると、相対パスとは今いるところ（ディレクトリ）から見た場合のパスを書く、とありますが、今いるところとはその都度変わるものなのではないでしょうか？
また、自分が今作業しているところはCustomerInfo.csv だと思うんですが、、

**Comment by LunaChevalier** [comment]
プログラムがあるディレクトリは必ずしも今のディレクトリにあるわけではありません  
なので、プログラムが動作するディレクトリによっては相対パスは変化します(伝わるかな…)

**Comment by hibikisameta** [comment]
すみません、完璧には理解出来ずなんとなくしか分からないです。

プログラムが今自分のパソコン上では
　　C:\Users\ 以下省略
にありますが、これだと他の人が全く同じルートを通らないと開けないということですよね。

なので、誰がどんなディレクトリを勝手に開いていようとプログラムを開くことが出来ないといけない。しかし、その書き方が調べても全く見えてきませんでした。
　　../../CustomerInfo.csv　とか？

**Comment by hibikisameta** [comment]
再度調べます。

**Comment by hibikisameta** [comment]
やはり、休日にも調べてみましたがどうしても理解出来ませんでした。

・相対パスの書き方はおそらく上記のものだろうと思いますが、どこまで表していいのか？

**Comment by LunaChevalier** [comment]
フォルダにsrcがあるので、その中にresourceフォルダを作って、そこにCSVファイルを格納して下さい  
とりあえず、そこにたどり着けるように相対パスを設定してみて下さい

**Comment by hibikisameta** [comment]
【報告】
説明してもらいましたが、格納後やはり記述に戸惑います。
また、エラーが出ました。

![image](https://user-images.githubusercontent.com/34155360/34347922-4df7b83e-ea4a-11e7-95b6-b4643f4a8ff8.png)

![image](https://user-images.githubusercontent.com/34155360/34347935-72112534-ea4a-11e7-8ef1-a1ce891ee064.png)

**Comment by hibikisameta** [comment]
相対パスの設定をしてみました。
しかし、未だに java.io.FileNotFoundException とエラーが出るので、それの原因を今から調べます。

![image](https://user-images.githubusercontent.com/34155360/34367609-19b56cd2-eaf0-11e7-873c-cf125352b760.png)

![image](https://user-images.githubusercontent.com/34155360/34367625-534aa520-eaf0-11e7-8187-3419905ee62d.png)

**Comment by hibikisameta** [comment]
未だに分かりませんので、昼上がりにもう一度検索します。

**Comment by LunaChevalier** [comment]
`../`でどのディレクトリにいるか把握してますか?  
↑でどういう移動が行われるかは理解しているはずなので、その時点でどこにいるか整理して下さい

**Comment by hibikisameta** [comment]
git の中の \src\elementProgram の FileManager.java から見て、../ で src ディレクトリにいます。
