### ISSUE TITLE
報告：csvファイルが消えました

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#34]
プログラムをまず完成させようと思って、FileWriter など使って書いてたんですが頭の中がごちゃごちゃしてきたので一旦それらを消して昨日の状態に戻しました。
そして実行してみたら、何も出なかったのでcsvファイルを確認のため開いてみました。
そしたら、csvファイルには触っていなかったのに中のデータが消えていました。
原因は全く分からないのですが、また作り直します。

**Comment by LunaChevalier** [comment]
どうやってプログラムやファイルを削除しましたか?

**Comment by hibikisameta** [comment]
プログラムは全てを削除したわけではないです。昨日出来ていた分に戻しただけです。
eclipse上で該当箇所をデリートしました。

ファイルはなぜ中身が消えていたのか分からないですが、開いた時にはもうまっさらな状態だったのでそのシートに再度自分で考えたデータを打ち込み保存しました。

**Comment by LunaChevalier** [comment]
消す前に、ファイルの書き込みの処理を動かしましたか?

**Comment by hibikisameta** [comment]
書き込みの処理というのは、一度書いてみたFileWriter などを消した、というのも含まれますか？
もし含むのであれば動かしました。

**Comment by LunaChevalier** [comment]
その時に同名のCSVファイルを空で上書きしたんでしょうね…

`git checkout CSVファイル名`で復元出来るとおもいま

**Comment by hibikisameta** [comment]
戻りました、ありがとうございました！
