### ISSUE TITLE
文字コード

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#35]
csvファイルを最初から作り直していたんですが、文字コードの指定が出来ていなくて文字化けします。
調べてて、このようなコードになったんですがこれでもまだ文字化けします。
java はUTF-8ですが、csvファイルの方は何なのか調べる方法を見つけることが出来ませんでした。

![image](https://user-images.githubusercontent.com/34155360/34289747-4d539666-e737-11e7-94a1-3a4a958d2387.png)

**Comment by hibikisameta** [comment]
再度調べます。

**Comment by hibikisameta** [comment]
やはり、休日にも調べてみましたがどうしても理解出来ませんでした。

・上記の手法以外で文字コードを変換させる方法があるのか？

**Comment by Dk-Roar** [comment]
秀丸エディタで開いて確認できるはずですー。

名前をつけて保存するときに文字コードを変換(指定)して保存することもできます。

詳しくは「秀丸エディタ 文字コード 変換」などでググってみてください(๑･̑◡･̑๑)

**Comment by hibikisameta** [comment]
ありがとうございます。
しかし、その手法はやってみた上で、InputStreamReader に("UTF-8") などの文字コードを記載する方法が検索した時に見つけたのでそれをやってみようとしてました。

文字コード指定の流れが完全に分かってないんだと思いますが、プログラム上で上記のように固定すれば勝手にjava とファイルの文字コードが一緒になる、と思い込んでいました。
Dk-Roar さんのやり方で行えば、こちらで文字コードを設定してしまえば次別のパソコンで使う人も文字化けが起こらない、ということでしょうか。
