### ISSUE TITLE
保存場所

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#4]
develop/AgainstNumberGameとdevelop/PrimeNumberに関して、先日保存場所を聞かなかったんですが、git-bashなどがあるファイルに保存しない方がいいですよね？

自分は今のところ、「お気に入り」の「ダウンロード」に保存しようかと考えています。

**Comment by LunaChevalier** [comment]
保存場所は`elementProgram`で一元管理されれるので、別にしなくていいです(というか、別にしたらダメ)  
ブランチを変えたら、それに合わせてファイルの中身が変わる仕組みになってます

**Comment by hibikisameta** [comment]
了解しました。
続けてやってみます。
