### ISSUE TITLE
謝罪

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#5]
本日提出予定だった、課題を終わらせることが出来ませんでした。
どこが不明確なのか、よく自分でもはっきりしないところがあるのでお二人の手を煩わせることになりそうです。
どこがダメなのか、自分でもやりますので明日以降もまたよろしくお願いします。

ちなみに今日どこで躓いたかというと、最初の段階のaddで
　　add C:\Users\ry-fukamaki\Desktop\git\elementProgram（ファイル名）
のところです。

**Comment by LunaChevalier** [comment]
了解しましたー

>ちなみに今日どこで躓いたかというと、最初の段階のaddで
>　　add C:\Users\ry-fukamaki\Desktop\git\elementProgram（ファイル名）
>のところです。

ですが
* `git`コマンドを実行する場合，必ず先頭に`git`がつく
* ファイル名はフルパスが使えず，指定できるのは`status`で表示されたパスになる
と思うので，それで試して下さい(wikiに説明が漏れていたので，追記しておきます)

後，タイトルは中身がわかるような名前にお願いします(今回なら12/4の報告とか)

**Comment by LunaChevalier** [comment]
上のことを試す前に，アカウントに紐付いているメールにpushするできるようなる旨のメールが届いていると思うので，先にそっちの認証を完了してからでお願いします

**Comment by LunaChevalier** [comment]
pushできるの確認しました  
謎のブランチ名はさっさと削除します
