### ISSUE TITLE
7/11 Javadocコメントについて

### ISSUE THREAD

**Issue by dfjkyrcq** [LunaChevalierGroup/elementProgram#50]
【疑問点】
Javadocコメントの書き方がわからないので、調べて書いてみます。

- [ ] @LunaChevalier
- [ ] @Dk-Roar

**Comment by LunaChevalier** [comment]
書き方はわかりましたか?  
もしわかったら，参考にしたサイトを教えてください

**Comment by dfjkyrcq** [comment]
https://www.javadrive.jp/javadoc/comment/index1.html
コメントの構成-コメントの書式-Javadocの記述を参考にしました。
