### ISSUE TITLE
 7/12 課題：ファイル入出力

### ISSUE THREAD

**Issue by dfjkyrcq** [LunaChevalierGroup/elementProgram#53]
【疑問点】
ファイル入出力の課題をしようと思っているのですが、CSVファイルについてよくわかりません。

- [ ] @LunaChevalier
- [ ] @Dk-Roar

**Comment by dfjkyrcq** [comment]
CSVファイルがどういうものなのかについては理解することができました。
課題の内容については理解することができませんでした。

**Comment by LunaChevalier** [comment]
では，CSVがどのようなものかここで説明してください

**Comment by dfjkyrcq** [comment]
カンマで値を区切った値が入っているファイルで、異なるアプリケーションでも開くことができるものであると学習しました。
