### ISSUE TITLE
7/17 ファイル入出力課題

### ISSUE THREAD

**Issue by dfjkyrcq** [LunaChevalierGroup/elementProgram#59]
【疑問点】
ファイル入出力課題で書き込み処理とは各行の先頭に行数を追加することで、
編集処理とは、各行の先頭に追加した行数をCSVファイルに追加することという認識でよろしいですか。

- [x] @LunaChevalier
- [x] @Dk-Roar

**Comment by Dk-Roar** [comment]
### 書き込み処理について
書き込み処理は文字通り、CSVファイルに文字列を書き込む処理のことです。
ファイル読み込み→読み込んだデータを編集→ファイルに書き込み　という流れのイメージです。

### 編集処理について
上でも少し触れましたが、読み込んだデータに対して内容の変更などの操作を行う処理が編集処理になります。


@LunaChevalier 認識齟齬あったら指摘お願いします :bow:

**Comment by LunaChevalier** [comment]
合ってマース
