### ISSUE TITLE
12/5の宿題

### ISSUE THREAD

**Issue by Dk-Roar** [LunaChevalierGroup/elementProgram#6]
課題の状況(着手、未着手など)を教えてほしいです。

【未着手の場合】
・書籍はどこまで読んでいるか
・いつ頃着手できそうか
以上2点の報告

【着手している場合】
・どの課題を選んだか
・つまづいた点(あれば)
・フローチャート図を作成
上記3点の報告

よろしくおねがいしますー。

**Comment by LunaChevalier** [comment]
> フローチャート図を作成

まずは3つの内どれか1つでお願いします

**Comment by LunaChevalier** [comment]
午後からレビューしたいので、未完成でもいいのでフローチャートの提出をお願いしまーす

**Comment by hibikisameta** [comment]
チェックよろしくお願いします。

![image](https://user-images.githubusercontent.com/34155360/33591273-01015c8e-d9c8-11e7-899e-9f528f7009bc.png)

**Comment by LunaChevalier** [comment]
取り急ぎ、ロジックに関する部分で良くないところだけ書いときます  

* FizzやBuzzを出力する順序がよろしく無いですね…  
15が入るとFizzしか出力されないです
* 1ループした時に何も処理がないので、同じ値で判定し続け無限ループに陥ります  
* ループの終了条件がありません  
察するに`i = 100`の部分が終了条件になると思いますが、四角なので`i`に100が入るだけになります
* 課題の仕様から外れている部分があります  
最後の値は入力された値になるので、勝手に100に固定するのはダメです…

指摘箇所は修正してもらいますが、修正中に引っかかったらその都度issue立てて、最終的な図を一部分でもいいので貼り付ける様お願いします

他は後に書きます

**Comment by hibikisameta** [comment]
選んだ課題…FizzBuzz

【本日の報告】
・昨日課題のやり方が分からず時間を消費したために終わらなかった、Java参考書を進めました。
　そのため、今日はフローチャートのみ着手済み。
・参考書は10章の「クラスの利用」まで手を付けています。
・フローチャートが終わってからなので、明日の3時以降か明後日には着手します。

ありがとうございます。了解しました。
