### ISSUE TITLE
ブラックジャック課題について

### ISSUE THREAD

**Issue by dfjkyrcq** [LunaChevalierGroup/elementProgram#72]
ブラックジャックの課題を拝見しましたが、前回までの内容と比べかなり難易度が高く感じております。何から手をつければよいでしょうか。

**Comment by LunaChevalier** [comment]
とりあえず、いきなりプログラムを書かずに何が必要なのかを考えます  
まずは、ブラックジャックのルールを考えずに、必要なものや人をイメージして、それらがどんなことをできるようになればブラックジャックが成立するか、紙や図に整理してみるところからしてみてはどうでしょう?

**Comment by LunaChevalier** [comment]
図など↑を整理したドキュメントができたら、このissueに上げてください

**Comment by dfjkyrcq** [comment]
[ブラックジャック.xlsx](https://github.com/LunaChevalierGroup/elementProgram/files/2226097/default.xlsx)
