### ISSUE TITLE
7/25 ブラックジャック課題：トランプについて

### ISSUE THREAD

**Issue by dfjkyrcq** [LunaChevalierGroup/elementProgram#74]
トランプの作成をしようと思い、列挙型でトランプを52枚作りました。これをlistに入れてトランプを配るプログラムを作成しようとしていますが、その作成方法分からずまだ作成できておりませんので調査をしております。

**Comment by dfjkyrcq** [comment]
解決しました。

**Comment by LunaChevalier** [comment]
解決方法を教えて下さい

**Comment by dfjkyrcq** [comment]
valuesメソッドでTramp[]型の変数trampに列挙型の配列を代入し、for文でtrampの配列の長さだけlistにadd
することで解決しました。
