### ISSUE TITLE
12/5の宿題　修正1

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#8]
出力する順序と1ループ後の処理はやってみました。
添削よろしくお願いします。

【ループに関する疑問点】
最後の数値は入力された値になりますが、その書き方が検索しても分かりませんでした。
自分で何回繰り返す、と分かっている場合は参考書にありますが、、、

**Comment by hibikisameta** [comment]
![image](https://user-images.githubusercontent.com/34155360/33640903-9424c7e0-da76-11e7-84a7-2ff6f82b2f41.png)

**Comment by Dk-Roar** [comment]
すみません、遅くなりました:bow:

ほぼほぼ問題なさそうです！おつかれさまです！


> 最後の数値は入力された値になりますが、その書き方が検索しても分かりませんでした。
入力した値を保持する変数を１つ用意して、処理開始の次でその変数に値を入力してもらうことでできます。

ループのフローの書き方については以下のサイトが参考になると思います
http://masudahp.web.fc2.com/flowchart/algo002.html

**Comment by Dk-Roar** [comment]
指摘した部分がしっかり修正されてて素晴らしいですね〜。

処理の流れは把握できてそうなので、次のステップに進んでもらいたいと思います！

このフローチャートをプログラムに書き出して提出をおねがいします。

**Comment by Dk-Roar** [comment]
ソースは各ブランチにpushすることで提出してもらいたいです。

Issueには、
・どのくらいかけたか
・つまづいたところ
・困っていること
などを書き込んでください(๑･̑◡･̑๑)

ソースのコミットやプッシュがうまくいかないときはまた連絡をおねがいします。

**Comment by Dk-Roar** [comment]
補足です

gitの操作(コミット、プッシュなど)はじわじわ慣れて貰えばよいので、すぐすぐできなくても大丈夫です！

うまくいかなかったらその旨をissueに書いてもらって、ソースを書く方に尽力してください〜

**Comment by hibikisameta** [comment]
お疲れ様です、ただ今お昼休憩から戻ってきました。

ありがとうございます。有田さんから見てほぼ問題ないということなので大丈夫ではあるんでしょうが、なんか自分の中でまだしっくりきてない部分があるんですよね、、、
　→「I++」から矢印が下にも左にもいけるように書いてるのが分かりにくい気がします！

今は先に進めていきますね。

**Comment by hibikisameta** [comment]
あとgit, githubの操作がなかなか上手くいかず質問攻めになってしまうので、githubの本を自己学習用として購入しました。
社内にはさすがに関連書籍が置いてなかったので、これから並行して読んでいこうと思います！

**Comment by Dk-Roar** [comment]
そもそもループの記号で囲まれているので、ループの終了条件を満たすまではループの始まりに戻ります。

なので、i++の処理から上に戻る矢印がそもそも不要となります。

i++をする→ループの端まで来る→終了条件を満たしていない→ループの頭まで戻る→〜

という感じですね

**Comment by Dk-Roar** [comment]
それはそうと、書籍購入したんですね！

モチベーション高くて素晴らしいです！ 

本の代金は経費で出せるかもなので、今度相談しましょう〜。

**Comment by hibikisameta** [comment]
ありがとうございます。
今後気を付けたいと思いますので、コードを出来るだけ進めてみます。

**Comment by Dk-Roar** [comment]
いえいえ、めちゃ順調に進んでいるんで自信持ってください(๑･̑◡･̑๑)

ファイトでーす🏴

**Comment by LunaChevalier** [comment]
> あとgit, githubの操作がなかなか上手くいかず質問攻めになってしまうので、githubの本を自己学習用として購入しました。

お，素晴らしいですね!  
もしよかったら，出版社と本のタイトルを教えてくだーい

**Comment by hibikisameta** [comment]
「GitHub 実践入門」大塚弘記・著　技術評論社

![image](https://user-images.githubusercontent.com/34155360/33694453-893e8684-db3b-11e7-9ccf-4cda10ca4c05.png)

**Comment by hibikisameta** [comment]
これはgitというよりもgithubに特化しているらしく、今の自分にちょうどいいと思って購入しました。

ちなみに値段は、2580円+税です！
