### ISSUE TITLE
github上での課題の報告方法

### ISSUE THREAD

**Issue by hibikisameta** [LunaChevalierGroup/elementProgram#9]
javaを書くのはeclipseで書き、githubではnew repositoryを作成すればいいんでしょうか？
一連の流れがまだよく把握出来ておらず、どこで何をすればいいのか戸惑ってしまいます。

こんな感じかな？と思いましたので、一応参照よろしくお願いします。
https://qiita.com/cotrpepe/items/7cafaacb538425a78f1f

**Comment by Dk-Roar** [comment]
ちょっと複雑なので図解したいんですが、出先からじゃ厳しいので帰ってから貼りまーす！

いまはコード書く方に専念してください:now:

**Comment by Dk-Roar** [comment]
:bow:

**Comment by Dk-Roar** [comment]
すいません、色々あってかけてません(´･ω･`)

今夜には書きます…

**Comment by hibikisameta** [comment]
はい、よろしくお願いします！
